apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: okmnojn4a-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/okmnojn4a-dotnet-basic-gitops